### ISSUE TITLE
项目整体规划路线

### ISSUE THREAD

**Issue by kylezhang** [kuangshp/cms-egg-api#1]
挺好的；
有项目整体的规划路线吗？

**Comment by kuangshp** [comment]
用nodejs后台管理系统的种子文件项目,仅仅是提供用户登录、用户管理、角色管理、资源管理、上传附件的基本功能,不同项目需求，可以在种子项目的基础上继续添砖加瓦

**Comment by kylezhang** [comment]
> 用nodejs后台管理系统的种子文件项目,仅仅是提供用户登录、用户管理、角色管理、资源管理、上传附件的基本功能,不同项目需求，可以在种子项目的基础上继续添砖加瓦

说的没错，但是一个成功的，有活力，让大家都能参与的项目，不仅只是代码，还有大量的文档和周边环境等。
多看写其他的做的好的开源项目，而且参与人多的。
